http:
  enabled: false
input:
  centrifuge_input:
    endpoint: ws://localhost:8079/connection/websocket
    channel: chat:index
    batching:
      count: 3
      period: 60s
      processors:
        - archive:
            format: binary

pipeline:
  threads: 1

output:
  justlogit:
    max_in_flight: 1
logger:
  level: ${LOG_LEVEL}
  format: json
  add_timestamp: true
  static_fields:
    "@service": centrifuge_input
