input:
  kafka:
    addresses: ["localhost:9093"]
    topics: ["cloudevents-core"]
    consumer_group: "$Default2"    
    multi_header: true
    batching:
      count: 3
      period: 20s
      processors:
        - archive:
            format: binary
            
pipeline:
  threads: 1
  processors:
  - sleep:
      duration: 1s
 
 

output:
  cloudevents_grpc: 
    grpc_url: "localhost:9050"
    max_in_flight: 64
    kafka_franz_dead_letter:
      seed_brokers: ["localhost:9093"]
      topic: "cloudevents-core-deadletter"
     
    # auth[optional] one of: [oauth2,basic,apikey](ordered by priority)
    #--------------------------------------------------------------------
    #auth:
    #  basic:
    #    user_name: "admin"
    #    password: "password"
    #  oauth2:
    #    client_id: "my_client_id"
    #    client_secret: "secret"
    #    token_endpoint: "https://example.com/oauth2/token"
    #    scopes: ["scope1", "scope2"]
    #  apikey:
    #    name: "x-api-key"
    #    value: "secret"