// Code generated by protoc-gen-go-fluffycore-di. DO NOT EDIT.

package centrifuge

import (
	context "context"
	fluffy_dozm_di "github.com/fluffy-bunny/fluffy-dozm-di"
	endpoint "github.com/fluffy-bunny/fluffycore/contracts/endpoint"
	dicontext "github.com/fluffy-bunny/fluffycore/middleware/dicontext"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
)

// IFluffyCoreCentrifugePositionServiceServer defines the grpc server
type IFluffyCoreCentrifugePositionServiceServer interface {
	CentrifugePositionServiceServer
}

type UnimplementedFluffyCoreCentrifugePositionServiceServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreCentrifugePositionServiceServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// CentrifugePositionServiceFluffyCoreServer defines the grpc server truct
type CentrifugePositionServiceFluffyCoreServer struct {
	UnimplementedCentrifugePositionServiceServer
	UnimplementedFluffyCoreCentrifugePositionServiceServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *CentrifugePositionServiceFluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterCentrifugePositionServiceServer(s, srv)
}

// AddCentrifugePositionServiceServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddCentrifugePositionServiceServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreCentrifugePositionServiceServer](cb, ctor)
}

// AddCentrifugePositionServiceServer adds the fluffycore aware grpc server
func AddCentrifugePositionServiceServer(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddCentrifugePositionServiceServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &CentrifugePositionServiceFluffyCoreServer{}
	})
}

// StoreStreamPosition...
func (s *CentrifugePositionServiceFluffyCoreServer) StoreStreamPosition(ctx context.Context, request *StoreStreamPositionRequest) (*StoreStreamPositionResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreCentrifugePositionServiceServer](requestContainer)
	return downstreamService.StoreStreamPosition(ctx, request)
}

// GetStreamPosition...
func (s *CentrifugePositionServiceFluffyCoreServer) GetStreamPosition(ctx context.Context, request *GetStreamPositionRequest) (*GetStreamPositionResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreCentrifugePositionServiceServer](requestContainer)
	return downstreamService.GetStreamPosition(ctx, request)
}
