// Code generated by protoc-gen-go-fluffycore-di. DO NOT EDIT.

package kafkacloudevent

import (
	context "context"
	fluffy_dozm_di "github.com/fluffy-bunny/fluffy-dozm-di"
	endpoint "github.com/fluffy-bunny/fluffycore/contracts/endpoint"
	dicontext "github.com/fluffy-bunny/fluffycore/middleware/dicontext"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
)

// IKafkaCloudEventServiceServer defines the grpc server
type IKafkaCloudEventServiceServer interface {
	KafkaCloudEventServiceServer
}

type UnimplementedKafkaCloudEventServiceServerEndpointRegistration struct {
}

func (UnimplementedKafkaCloudEventServiceServerEndpointRegistration) RegisterHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// KafkaCloudEventServiceFluffyCoreServer defines the grpc server truct
type KafkaCloudEventServiceFluffyCoreServer struct {
	UnimplementedKafkaCloudEventServiceServer
	UnimplementedKafkaCloudEventServiceServerEndpointRegistration
}

// Register the server with grpc
func (srv *KafkaCloudEventServiceFluffyCoreServer) Register(s *grpc.Server) {
	RegisterKafkaCloudEventServiceServer(s, srv)
}

// AddKafkaCloudEventServiceServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddKafkaCloudEventServiceServerWithExternalRegistration[T IKafkaCloudEventServiceServer](cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IKafkaCloudEventServiceServer](cb, ctor)
}

// AddKafkaCloudEventServiceServer adds the fluffycore aware grpc server
func AddKafkaCloudEventServiceServer[T IKafkaCloudEventServiceServer](cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddKafkaCloudEventServiceServerWithExternalRegistration[IKafkaCloudEventServiceServer](cb, ctor, func() endpoint.IEndpointRegistration {
		return &KafkaCloudEventServiceFluffyCoreServer{}
	})
}

// SubmitCloudEvents...
func (s *KafkaCloudEventServiceFluffyCoreServer) SubmitCloudEvents(ctx context.Context, request *SubmitCloudEventsRequest) (*SubmitCloudEventsResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IKafkaCloudEventServiceServer](requestContainer)
	return downstreamService.SubmitCloudEvents(ctx, request)
}
