// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: pkg/proto/kafkacloudevent/kafkacloudevent.proto

package kafkacloudevent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KafkaCloudEventService_SubmitCloudEvents_FullMethodName = "/pkg.proto.kafkacloudevent.KafkaCloudEventService/SubmitCloudEvents"
)

// KafkaCloudEventServiceClient is the client API for KafkaCloudEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KafkaCloudEventServiceClient interface {
	// submits a batch of cloud events
	SubmitCloudEvents(ctx context.Context, in *SubmitCloudEventsRequest, opts ...grpc.CallOption) (*SubmitCloudEventsResponse, error)
}

type kafkaCloudEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKafkaCloudEventServiceClient(cc grpc.ClientConnInterface) KafkaCloudEventServiceClient {
	return &kafkaCloudEventServiceClient{cc}
}

func (c *kafkaCloudEventServiceClient) SubmitCloudEvents(ctx context.Context, in *SubmitCloudEventsRequest, opts ...grpc.CallOption) (*SubmitCloudEventsResponse, error) {
	out := new(SubmitCloudEventsResponse)
	err := c.cc.Invoke(ctx, KafkaCloudEventService_SubmitCloudEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KafkaCloudEventServiceServer is the server API for KafkaCloudEventService service.
// All implementations must embed UnimplementedKafkaCloudEventServiceServer
// for forward compatibility
type KafkaCloudEventServiceServer interface {
	// submits a batch of cloud events
	SubmitCloudEvents(context.Context, *SubmitCloudEventsRequest) (*SubmitCloudEventsResponse, error)
	mustEmbedUnimplementedKafkaCloudEventServiceServer()
}

// UnimplementedKafkaCloudEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKafkaCloudEventServiceServer struct {
}

func (UnimplementedKafkaCloudEventServiceServer) SubmitCloudEvents(context.Context, *SubmitCloudEventsRequest) (*SubmitCloudEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCloudEvents not implemented")
}
func (UnimplementedKafkaCloudEventServiceServer) mustEmbedUnimplementedKafkaCloudEventServiceServer() {
}

// UnsafeKafkaCloudEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KafkaCloudEventServiceServer will
// result in compilation errors.
type UnsafeKafkaCloudEventServiceServer interface {
	mustEmbedUnimplementedKafkaCloudEventServiceServer()
}

func RegisterKafkaCloudEventServiceServer(s grpc.ServiceRegistrar, srv KafkaCloudEventServiceServer) {
	s.RegisterService(&KafkaCloudEventService_ServiceDesc, srv)
}

func _KafkaCloudEventService_SubmitCloudEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCloudEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KafkaCloudEventServiceServer).SubmitCloudEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KafkaCloudEventService_SubmitCloudEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KafkaCloudEventServiceServer).SubmitCloudEvents(ctx, req.(*SubmitCloudEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KafkaCloudEventService_ServiceDesc is the grpc.ServiceDesc for KafkaCloudEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KafkaCloudEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.proto.kafkacloudevent.KafkaCloudEventService",
	HandlerType: (*KafkaCloudEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCloudEvents",
			Handler:    _KafkaCloudEventService_SubmitCloudEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/kafkacloudevent/kafkacloudevent.proto",
}
